#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Dec 10 00:33:27 PST 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto baf12c9cc79b4d8f8e51ebe83caf142e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot n_k2ProcessorV1_0_sim_behav xil_defaultlib.n_k2ProcessorV1_0_sim xil_defaultlib.glbl -log elaborate.log"
xelab -wto baf12c9cc79b4d8f8e51ebe83caf142e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot n_k2ProcessorV1_0_sim_behav xil_defaultlib.n_k2ProcessorV1_0_sim xil_defaultlib.glbl -log elaborate.log

