#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Dec 10 00:33:28 PST 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim n_k2ProcessorV1_0_sim_behav -key {Behavioral:sim_1:Functional:n_k2ProcessorV1_0_sim} -tclbatch n_k2ProcessorV1_0_sim.tcl -view /home/cenema/Desktop/Xilinx_Projects/Exam2Debuggin_task3/n_k2ProcessorV1_0_sim_behav.wcfg -log simulate.log"
xsim n_k2ProcessorV1_0_sim_behav -key {Behavioral:sim_1:Functional:n_k2ProcessorV1_0_sim} -tclbatch n_k2ProcessorV1_0_sim.tcl -view /home/cenema/Desktop/Xilinx_Projects/Exam2Debuggin_task3/n_k2ProcessorV1_0_sim_behav.wcfg -log simulate.log

